/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Dialogs;

/**
 *
 * @author Marcelo
 */
public class AsignarPropiedad extends javax.swing.JDialog {

    /**
     * Creates new form AsignarPropiedad
     */
    public AsignarPropiedad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo_actualizacion = new javax.swing.ButtonGroup();
        indice_corrector = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dimension = new javax.swing.JTextField();
        cuota_total = new javax.swing.JTextField();
        aceptarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tipo_propiedad = new javax.swing.JComboBox<>();
        cantidad_cuotas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bolsa_cemento = new javax.swing.JTextField();
        barrio = new javax.swing.JComboBox<>();
        manzana = new javax.swing.JComboBox<>();
        comboCanalVenta = new javax.swing.JComboBox<>();
        apellido_propietario = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        nombre_propietario = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        fch_suscripción = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        bolsaCemento = new javax.swing.JRadioButton();
        empPublico = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        mensaje_error = new javax.swing.JLabel();
        cuota_fija = new javax.swing.JRadioButton();
        cuota_fija_vble = new javax.swing.JRadioButton();
        indice_si = new javax.swing.JRadioButton();
        indice_no = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        parcela = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        comboVendedor = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        suscripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar propiedad");
        setMinimumSize(new java.awt.Dimension(407, 510));
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Barrio/Torre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel2.setText("Manzana/Piso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabel3.setText("Parcela/Dpto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, 20));

        jLabel4.setText("Suscripción $");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        jLabel5.setText("Bolsa de cemento $");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 20));
        getContentPane().add(dimension, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, -1));

        cuota_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuota_totalActionPerformed(evt);
            }
        });
        getContentPane().add(cuota_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 230, -1));

        aceptarBtn.setText("Aceptar");
        getContentPane().add(aceptarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        cancelarBtn.setText("Cancelar");
        getContentPane().add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, -1));

        jLabel8.setText("Medio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 20));

        jLabel9.setText("Tipo propiedad");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        tipo_propiedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terreno", "Departamento" }));
        getContentPane().add(tipo_propiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 230, -1));

        cantidad_cuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad_cuotasActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad_cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 40, -1));

        jLabel10.setText("Cuota total $");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 20));
        getContentPane().add(bolsa_cemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 115, -1));

        getContentPane().add(barrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 230, -1));

        getContentPane().add(manzana, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 80, -1));

        comboCanalVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Volante", "Facebook", "Instagram", "Celular", "Cartel" }));
        getContentPane().add(comboCanalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 230, -1));

        getContentPane().add(apellido_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 230, -1));

        jLabel11.setText("Apellido Propietario");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        getContentPane().add(nombre_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 230, -1));

        jLabel12.setText("Nombre Propietario");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(fch_suscripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 139, -1));

        jLabel14.setText("Fecha suscripción");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        bolsaCemento.setText("Bolsa cemento");
        getContentPane().add(bolsaCemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        empPublico.setText("Emp. público");
        getContentPane().add(empPublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, 20));

        jLabel15.setText("Tipo actualización");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        mensaje_error.setForeground(new java.awt.Color(255, 0, 0));
        mensaje_error.setPreferredSize(new java.awt.Dimension(0, 17));
        getContentPane().add(mensaje_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 480, 240, 20));

        cuota_fija.setText("C. fija");
        getContentPane().add(cuota_fija, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        cuota_fija_vble.setText("C. fija (Variable)");
        cuota_fija_vble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuota_fija_vbleActionPerformed(evt);
            }
        });
        getContentPane().add(cuota_fija_vble, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        indice_si.setSelected(true);
        indice_si.setText("Si");
        indice_si.setEnabled(false);
        indice_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indice_siActionPerformed(evt);
            }
        });
        getContentPane().add(indice_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        indice_no.setText("No");
        indice_no.setEnabled(false);
        getContentPane().add(indice_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jLabel16.setText("Aplicar indice corrector");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 137, 10));

        getContentPane().add(parcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 70, -1));

        jLabel17.setText("Dimensión");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));

        comboVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(comboVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 230, -1));

        jLabel18.setText("Vendedor");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 20));
        getContentPane().add(suscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 90, -1));

        jLabel6.setText("Cantidad cuotas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuota_fija_vbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuota_fija_vbleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuota_fija_vbleActionPerformed

    private void indice_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indice_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indice_siActionPerformed

    private void cuota_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuota_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuota_totalActionPerformed

    private void comboVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboVendedorActionPerformed

    private void cantidad_cuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad_cuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidad_cuotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AsignarPropiedad dialog = new AsignarPropiedad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton aceptarBtn;
    public javax.swing.JComboBox<String> apellido_propietario;
    public javax.swing.JComboBox<String> barrio;
    public javax.swing.JRadioButton bolsaCemento;
    public javax.swing.JTextField bolsa_cemento;
    public javax.swing.JButton cancelarBtn;
    public javax.swing.JTextField cantidad_cuotas;
    public javax.swing.JComboBox<String> comboCanalVenta;
    public javax.swing.JComboBox<String> comboVendedor;
    public javax.swing.JRadioButton cuota_fija;
    public javax.swing.JRadioButton cuota_fija_vble;
    public javax.swing.JTextField cuota_total;
    public javax.swing.JTextField dimension;
    public javax.swing.JRadioButton empPublico;
    public com.toedter.calendar.JDateChooser fch_suscripción;
    public javax.swing.ButtonGroup indice_corrector;
    public javax.swing.JRadioButton indice_no;
    public javax.swing.JRadioButton indice_si;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JComboBox<String> manzana;
    public javax.swing.JLabel mensaje_error;
    public javax.swing.JComboBox<String> nombre_propietario;
    public javax.swing.JComboBox<String> parcela;
    public javax.swing.JTextField suscripcion;
    public javax.swing.ButtonGroup tipo_actualizacion;
    public javax.swing.JComboBox<String> tipo_propiedad;
    // End of variables declaration//GEN-END:variables
}
