/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Dialogs;

/**
 *
 * @author Marceloi7
 */
public class ModificarCuota extends java.awt.Dialog {

    /**
     * Creates new form ActualizarCuota
     */
    public ModificarCuota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cuota_total = new javax.swing.JTextField();
        porcentaje_gastos = new javax.swing.JTextField();
        gastos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cancelarBtn = new javax.swing.JButton();
        aceptarBtn = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();

        setTitle("Actualizar cuota");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(null);
        jPanel1.add(cuota_total);
        cuota_total.setBounds(120, 50, 90, 22);
        jPanel1.add(porcentaje_gastos);
        porcentaje_gastos.setBounds(120, 90, 90, 22);
        jPanel1.add(gastos);
        gastos.setBounds(120, 130, 90, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Gastos $");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 130, 60, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("% Gastos");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 90, 70, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cuota total $");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 50, 80, 17);

        cancelarBtn.setText("Cancelar");
        jPanel1.add(cancelarBtn);
        cancelarBtn.setBounds(140, 190, 90, 25);

        aceptarBtn.setText("Aceptar");
        jPanel1.add(aceptarBtn);
        aceptarBtn.setBounds(40, 190, 90, 25);

        aviso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aviso.setForeground(new java.awt.Color(255, 0, 0));
        aviso.setText("No se pudo actualizar");
        jPanel1.add(aviso);
        aviso.setBounds(70, 230, 150, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarCuota dialog = new ModificarCuota(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton aceptarBtn;
    public javax.swing.JLabel aviso;
    public javax.swing.JButton cancelarBtn;
    public javax.swing.JTextField cuota_total;
    public javax.swing.JTextField gastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField porcentaje_gastos;
    // End of variables declaration//GEN-END:variables
}
